
server:
  port: 8085

spring:
  application:
    name: Api-gateway       # API-GATEWAY Config


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/users

        - id: ACTIVITYTRACK-SERVICE
          uri: lb://ACTIVITYTRACK-SERVICE
          predicates:
            - Path=/api/activity/**
          filters:
            - name: CircuitBreaker
              args:
                name: activityServiceCircuitBreaker
                fallbackUri: forward:/fallback/activity

        - id: AI-SERVICE
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendation/**
          filters:
            - name: CircuitBreaker
              args:
                name: aiServiceCircuitBreaker
                fallbackUri: forward:/fallback/recommendation
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  http://localhost:8088/realms/fitness-Tracker-Oath/protocol/openid-connect/certs
#  webflux:
#    base-path: /fallback


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

